### PR TITLE
Fix liquidity pool balance deserialization.

### PR DESCRIPTION
**Pull request by Heteroculturalism**
## Types of changes

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [   ] New feature (non-breaking change which adds functionality)
- [   ] Breaking change (fix or feature that would cause existing functionality to change)
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] My code follows the code style of this project.
- [   ] My change requires a change to the documentation.
- [   ] I have updated the documentation accordingly.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

### CODE REVIEW

**Comment by elucidsoft** [comment]
LGTM

**Comment by elucidsoft** [comment]
@Kirbyrawr Can you confirm?

**Review by Kirbyrawr — APPROVED** [review]
Looks good, love the fluent assertions

**Comment by Heteroculturalism** [comment]
I see the changes are approved, what is the merging process?  Do I need to do anything?

**Comment by Kirbyrawr** [comment]
Usually Eric is the one doing it.

**Pull request merged**
