### PR TITLE
Changed longs of ledger to ints.

### PR DESCRIPTION
**Pull request by Kirbyrawr**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by elucidsoft** [comment]
I'm not sure this change is correct.

**Comment by Kirbyrawr** [comment]
> 
> 
> I'm not sure this change is correct.

What exactly do you see that is wrong? I have my doubts too, but i want to compare.

**Comment by michaeljmonte** [comment]
I think the problem Eric is thinking about is that Horizon could potentially send a sequence number that is larger than in int.

**Comment by elucidsoft** [comment]
There is nothing wrong with your fix, but I am wondering if we should do
this or not.

**Comment by Kirbyrawr** [comment]
That's what i exactly said in Keybase, that we should be using long instead of int because of int limit

**Comment by elucidsoft** [comment]
Rejecting this PR

**Comment by Kirbyrawr** [comment]
Deleting branch as well

**Pull request closed without merging**
