### PR TITLE
Updated to work in a linux docker

### PR DESCRIPTION
**Pull request by chancity**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Gets ride of the PlatformNotSupportedException
`request.Proxy = null;`

Cause linux
`if (e.Data == "\"hello\"\r\n" || e.Data == "\"hello\"\n")`

### CODE REVIEW

**Comment by elucidsoft** [comment]
This fix makes sense, can we use Environment.NewLine instead though?  does that work?  We also need to add a unit test for this as code coverage is going down.

**Comment by chancity** [comment]
@elucidsoft Good point, I think Environment.NewLine would be a much cleaner way of doing this. I'll test it out tonight and let you know.  Is the unit test a side comment or is it something you'd like me to do for these two changes?

**Comment by elucidsoft** [comment]
That was a side comment, I just spent about 4 hours trying to get EventSource under unit test and that's a lost cause.  Basically EventSource needs to be completely rewritten using async/await and HttpClient but for now it will just have be as it is as that's a pretty significant effort.

**Comment by elucidsoft** [comment]
Upon inspection of this, you will need to update ALL RequestBuilders that support streaming.

**Comment by chancity** [comment]
I also noticed the EventSource doesn't change the Paging Token header and it will consistently fetch the last X operations/effects/transaction/etc.  Is this intended?

**Comment by elucidsoft** [comment]
I actually went ahead and refactored based on these changes you made here, please take a look at PR #72

**Comment by elucidsoft** [comment]
Streams do not use paging as the data is pushed to a Stream...It wouldn't make much sense to to setup a filter for a Stream that would always be in the past.  Streams are designed for monitoring real time data as it occurs on the network, you can setup filters to limit this data...

**Comment by chancity** [comment]
Hehe I just refractor a bit too...tell me what you think.

```  public class RequestBuilderExecuteable<T, TResponse> : RequestBuilder<T> where T : class where TResponse : class
    {
        public RequestBuilderExecuteable(Uri serverUri, string defaultSegment, HttpClient httpClient) : base(serverUri,
            defaultSegment, httpClient)
        {

        }

        ///<Summary>
        /// Build and execute request.
        /// </Summary>
        public async Task<Page<TResponse>> Execute()
        {
            return await Execute<Page<TResponse>>(BuildUri());
        }
    }

    public class RequestBuilderStreamable<T, TResponse> : RequestBuilderExecuteable<T, TResponse> where T :  class where TResponse : class
    {
        public RequestBuilderStreamable(Uri serverUri, string defaultSegment, HttpClient httpClient) : base(serverUri,
            defaultSegment, httpClient)
        {

        }

        ///<Summary>
        /// Allows to stream SSE events from horizon.
        /// Certain endpoints in Horizon can be called in streaming mode using Server-Sent Events.
        /// This mode will keep the connection to horizon open and horizon will continue to return
        /// responses as ledgers close.
        /// <a href="http://www.w3.org/TR/eventsource/" target="_blank">Server-Sent Events</a>
        /// <a href="https://www.stellar.org/developers/horizon/learn/responses.html" target="_blank">Response Format documentation</a>
        /// </Summary>
        /// <param name="listener">EventListener implementation with EffectResponse type</param> 
        /// <returns>EventSource object, so you can <code>close()</code> connection when not needed anymore</param> 
        public EventSource Stream(EventHandler<TResponse> listener)
        {
            var es = new EventSource(BuildUri());
            es.Message += (sender, e) =>
            {
                if (e.Data == $"\"hello\"{Environment.NewLine}")
                    return;

                var account = JsonSingleton.GetInstance<TResponse>(e.Data);
                listener?.Invoke(this, account);
            };

            return es;
        }
    }```

**Comment by chancity** [comment]
Let me know if you'd like me to submit a PR with those changes

**Comment by elucidsoft** [comment]
Yes it should be same behavior as Javascript version, I didn't realize it was different.

**Comment by elucidsoft** [comment]
There is a conflict in this PR, please resolve it.

**Comment by chancity** [comment]
@elucidsoft I opened a different PR with the refractoring I mentioned above!

**Pull request closed without merging**
