### PR TITLE
Added AccountResponse Data

### PR DESCRIPTION
**Pull request by Kirbyrawr**

### CODE REVIEW

**Comment by Kirbyrawr** [comment]
For test this, add this method to the Program.cs and call it.
```private static async Task ShowAccountData(Server server)
        {
            Console.WriteLine("-- Show Account Data --");

            var response = await server.Accounts.Account(KeyPair.FromAccountId("GA7BNH4ET3A472B2YIWIATM27XQSUF5OTJXA2FNM7DY2BB4VCOZKOC7B"));
            foreach (var item in response.Data)
            {
                Console.WriteLine(string.Concat("Key: ", item.Key, " - ", "Value: ", item.Value));
            }
            Console.WriteLine();
        }```

**Comment by elucidsoft** [comment]
Please add some tests to the AccountDeserializerTest class for this property.

**Comment by Kirbyrawr** [comment]
Will do!

**Comment by Kirbyrawr** [comment]
Should be ok now, let me know if there is anything more.
I saw that you made a guide for contributing, etc.. so i will be sure to follow that the next time.

**Pull request merged**
