### PR TITLE
Fixed null reference when converting a Transaction to an unsigned XDR

### PR DESCRIPTION
**Pull request by Kirbyrawr**
Fixed converting a transaction to a unsigned xdr object by adding an empty array.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] I have read the **CONTRIBUTING** document.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by Kirbyrawr** [comment]
I'm not sure why the codecoverage is failing, let me know if i need to do anything.

**Comment by elucidsoft** [comment]
It's failing because your change lowered code coverage. Try to add a unit test to test for your change.

**Comment by Kirbyrawr** [comment]
Thanks, i will do it!

**Comment by Kirbyrawr** [comment]
I added the tests, it seems it's better now.

**Pull request merged**
