### PR TITLE
Horizon 0.15.0 changes.

### PR DESCRIPTION
**Pull request by Kirbyrawr**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Kirbyrawr** [comment]
I'm not sure why the codecov is failing, probably because the Execute test, but i already added it, so not sure...

**Comment by elucidsoft** [comment]
- Looks like OperationFeesStatsResponse needs unit tests added.
- BaseOfferId and CounterOfferId in TradeResponse need the corresponding tests for TradeResponse updated to include tests for these two new properties.
- AuthImmutable property in Flags is not under any tests.

Once those issues are fixed the rest of it looks good and I will approve.

**Comment by Kirbyrawr** [comment]
Hi @elucidsoft AuthImmutable have a test here: https://github.com/elucidsoft/dotnet-stellar-sdk/blob/6540252567e679c302c5f742aaf143d9af72bea6/stellar-dotnet-sdk-test/responses/AccountDeserializerTest.cs#L35

**Comment by Kirbyrawr** [comment]
Also OperationFeeStatsResponse have tests here: https://github.com/elucidsoft/dotnet-stellar-sdk/blob/6540252567e679c302c5f742aaf143d9af72bea6/stellar-dotnet-sdk-test/responses/OperationFeeStatsDeserializerTest.cs

**Comment by Kirbyrawr** [comment]
And TradeResponse have tests for those properties here: https://github.com/elucidsoft/dotnet-stellar-sdk/blob/6540252567e679c302c5f742aaf143d9af72bea6/stellar-dotnet-sdk-test/responses/TradesPageDeserializerTest.cs#L31

**Pull request merged**
