### PR TITLE
Identity client version and name in headers

### LINKED ISSUE #152: Identify client SDK + version in request headers
As described in https://github.com/stellar/go/issues/725, it would be really helpful if this SDK sent two simple headers with each request, identifying the SDK and version:

> two headers are sent: client name (`X-Client-Name`) and version (`X-Client-Version`)

This will help maintainers of public Horizon instances understand where their traffic is coming from, and allow them to assess the impact of upgrading their Horizon version (for example they might delay upgrading to a version with breaking changes not handled by a client SDK with significant traffic to the server).

### PR DESCRIPTION
**Pull request by fracek**
Fix #152

(Sorry for the line end change as well)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by fracek** [comment]
We could hard code the values, I used reflection so the version number won't be ever out of sync.

**Comment by Kirbyrawr** [comment]
That's more clever than have it hardcoded, nothing more to say from my side, thanks!

**Comment by elucidsoft** [comment]
Looks fine, it would only get called during creation of a new HttpClient instance right?

**Comment by fracek** [comment]
Yes that's the case. If users don't want to send the identification information they can supply their own HttpClient as well and the headers won't be included.

**Pull request merged**
